#!/usr/sbin/env sh

FOLDER=$(basename $PWD)
EDITOR=${EDITOR:-nvim}
BUILDER=${BUILDER:-./dev.sh}

if tmux has-session 2> /dev/null; then
  CONNECT="new-window -n $FOLDER;"
  if [ -z "$TMUX" ]; then
    CONNECT="attach-session; new-window -n $FOLDER;"
  fi
else
  CONNECT="new-session -c $FOLDER -n $FOLDER;"
fi

tmux $CONNECT \
  send-keys "$EDITOR" C-m \; \
  split-window -h -c $PWD \; \
  resize-pane -x 40% \; \
  send-keys "${BUILDER}" C-m \; \
  split-window -v -c $PWD \; \
  resize-pane -y 30% \; \
  send-keys "git status" C-m \; \
  select-pane -t 0

